default_context:
  project_name: 'neoabacus'
  project_slug: 'neoabacus'
  domain_main: 'shopabacus.com'
  domain_staging: 'stag.shopabacus.com'
  docker_swarm_stack_name_main: 'shopabacus-com'
  docker_swarm_stack_name_staging: 'stag-shopabacus-com'
  secret_key: '8fc77e593b37efddeabb21dbe60fde4d76c7de16afd4f173b294e903f9133521'
  first_superuser: 'admin@shopabacus.com'
  first_superuser_password: '3ngineerThePlanet!'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.shopabacus.com", "https://stag.shopabacus.com", "https://shopabacus.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@shopabacus.com'
  postgres_password: 'neoPGpass!'
  pgadmin_default_user: 'admin@shopabacus.com'
  pgadmin_default_user_password: '3ngineerThePlanet!'
  traefik_constraint_tag: 'shopabacus.com'
  traefik_constraint_tag_staging: 'stag.shopabacus.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:3ngineerThePlanet!'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
